Vagrant.configure("2") do |config|
  config.vm.hostname = "coreos"

  config.vm.box = "coreos-stable"
  config.vm.box_url = "https://stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant_virtualbox.json"

  # always use Vagrants insecure key: false
  config.ssh.insert_key = false
  # forward ssh agent to easily ssh into the different machines
  config.ssh.forward_agent = true
  #config.ssh.keys_only = true
  #config.ssh.insert_key = true
  #config.ssh.username = "coreos"
  #config.ssh.password = "vagrant"

  config.vm.network "private_network", ip: "192.168.250.12"

  #k8s master nodes
  #config.vm.provision "shell", path: "master.sh
  
  k8s worker nodes
  #config.vm.provision "shell", path: "worker.sh
end

