Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "devops"

  config.vm.network "private_network", ip: "192.168.250.10"

  config.vm.synced_folder "C:\\MySpace", "/myspace"

  config.vm.provision "shell", inline: <<-SHELL
     yum update -y
     yum install -y wget
     yum install -y git
     yum install -y java-1.8.0-openjdk-devel

     #sudo vi /etc/profile
     #export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
     #export JRE_HOME=/usr/lib/jvm/jre
     #source /etc/profile
  SHELL


  #install nexus oss3, jenkins, gitlab; zookeeper, kafka; postgres; openldap
  #config.vm.provision "shell", path: "postgres.sh"
  #config.vm.provision "file", source: "postgresDB.sql", destination: "postgresDB.sql"

  config.vm.provider "virtualbox" do |vb|
     vb.gui=false
     vb.memory = 2048
     vb.cpus = 2
     vb.name = "devops"
  end
end
